name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:    [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  deploy-staging:
    runs-on: ubuntu-latest
    environment: Staging
    if: ${{ github.event_name == 'release' }}
    
    steps:
    - name: Deploy to Staging
      run: echo "Deploying to Staging"

  deploy-production:
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event_name == 'release' }}
    
    steps:
    - name: Deploy to Production
      run: echo "Deploying to Production"
